-- Oracle DB 초기화 스크립트
-- 애플리케이션 사용자 스키마에서 실행
-- 모의해킹 플랫폼용 기본 스키마 및 테이블 생성
-- schema.sql과 완전 호환 버전
-- 
-- 주의: gvenzl/oracle-xe 이미지가 APP_USER/APP_USER_PASSWORD 환경변수로
--       사용자를 자동 생성하고 이 스크립트를 해당 사용자로 실행합니다

-- 기존 테이블이 있다면 삭제 (개발 환경용)
-- Oracle에서는 IF EXISTS를 직접 지원하지 않으므로 예외 처리 방식 사용
DECLARE
    table_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(table_not_exist, -942);
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FILES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN table_not_exist THEN NULL;
END;
/

DECLARE
    table_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(table_not_exist, -942);
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN table_not_exist THEN NULL;
END;
/

DECLARE
    table_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(table_not_exist, -942);
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BOARDS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN table_not_exist THEN NULL;
END;
/

DECLARE
    table_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(table_not_exist, -942);
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN table_not_exist THEN NULL;
END;
/

DECLARE
    seq_not_exist EXCEPTION;
    PRAGMA EXCEPTION_INIT(seq_not_exist, -2289);
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ';
EXCEPTION
    WHEN seq_not_exist THEN NULL;
END;
/

-- USERS 테이블 생성 (schema.sql과 동일한 구조)
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20),
    BUSINESS_TOKEN VARCHAR2(255),
    CREATED_AT TIMESTAMP(6)
);

-- USERS 테이블용 시퀀스 생성
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- USERS 테이블용 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

-- BOARDS 테이블 생성 (schema.sql과 동일한 구조)
CREATE TABLE BOARDS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200),
    CONTENT CLOB,
    USER_ID NUMBER,
    CREATED_AT TIMESTAMP,
    IS_NOTICE NUMBER(1) DEFAULT 0
);

-- COMMENTS 테이블 생성
CREATE TABLE COMMENTS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  USER_ID NUMBER,
  CONTENT CLOB,
  CREATED_AT TIMESTAMP
);

-- FILES 테이블 생성
CREATE TABLE FILES(
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  FILE_NAME VARCHAR2(255),
  FILE_PATH VARCHAR2(255),
  UPLOADED_AT TIMESTAMP,
  UPLOADED_BY NUMBER
);

-- 외래키 제약조건 추가 (선택사항 - 팀 협의 후 결정)
-- 데이터 무결성 보장 vs 개발 편의성 중 선택
-- 운영 환경 시뮬레이션을 위해서는 추가 권장

/*
ALTER TABLE BOARDS ADD CONSTRAINT FK_BOARDS_USER_ID 
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_BOARD_ID 
    FOREIGN KEY (BOARD_ID) REFERENCES BOARDS(ID);
    
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENTS_USER_ID 
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE FILES ADD CONSTRAINT FK_FILES_BOARD_ID 
    FOREIGN KEY (BOARD_ID) REFERENCES BOARDS(ID);
    
ALTER TABLE FILES ADD CONSTRAINT FK_FILES_UPLOADED_BY 
    FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID);
*/

COMMIT; 