-- Oracle DB 초기화 스크립트 (gvenzl/oracle-free:slim용 - 개발 환경)
-- 테이블 생성 스크립트 (사용자는 APP_USER 환경변수로 자동 생성됨)
-- 개발용 계정: play / ground

-- gvenzl/oracle-free 이미지는 FREEPDB1 사용
ALTER SESSION SET CONTAINER = FREEPDB1;

-- 애플리케이션 사용자로 전환 (APP_USER 환경변수로 이미 생성됨)
ALTER SESSION SET CURRENT_SCHEMA = play;

-- 기존 테이블 삭제 (안전하게)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FILES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BOARDS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- USERS 테이블 생성 (schema.sql과 동일한 구조)
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20),
    CREATED_AT TIMESTAMP(6)
);

-- USERS 테이블용 시퀀스 생성
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

-- USERS 테이블용 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

-- BOARDS 테이블 생성 (schema.sql과 동일한 구조)
CREATE TABLE BOARDS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200),
    CONTENT CLOB,
    USER_ID NUMBER,
    CREATED_AT TIMESTAMP,
    IS_NOTICE NUMBER(1) DEFAULT 0
);

-- COMMENTS 테이블 생성
CREATE TABLE COMMENTS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  USER_ID NUMBER,
  CONTENT CLOB,
  CREATED_AT TIMESTAMP
);

-- FILES 테이블 생성
CREATE TABLE FILES(
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  FILE_NAME VARCHAR2(255),
  FILE_PATH VARCHAR2(255),
  UPLOADED_AT TIMESTAMP,
  UPLOADED_BY NUMBER
);

-- 테이블 생성 완료 확인
SELECT 'Tables created successfully in FREEPDB1 for user play' AS STATUS FROM DUAL;
SELECT TABLE_NAME FROM USER_TABLES;

-- 시나리오용 고정 계정 생성
-- 관리자 계정 생성
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE, CREATED_AT) 
VALUES (1, 'admin', '85f455ba36624ed0f6a0751189f8e2b1', 'ADMIN', SYSTIMESTAMP);

-- 기업 회원 계정 생성
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE, CREATED_AT) 
VALUES (2, 'bob_edu', 'bed128365216c019988915ed3add75fb', 'BUSINESS', SYSTIMESTAMP);

-- 시나리오용 공지사항 생성 (관리자 ID 힌트 제공)
INSERT INTO BOARDS (TITLE, CONTENT, USER_ID, CREATED_AT, IS_NOTICE) 
VALUES ('시스템 점검 안내', 
        '안녕하세요. 시스템 관리자입니다.<br>EduBot 제품 관련 정기 보안 점검을 실시합니다.<br>문의사항은 관리자에게 연락바랍니다.', 
        1, 
        SYSTIMESTAMP, 1);

-- 시퀀스 값 조정 (다음 일반 사용자는 ID 3부터 시작)
ALTER SEQUENCE USERS_SEQ RESTART START WITH 3;

COMMIT; 