// users 테이블 생성문
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20),
    BUSINESS_TOKEN VARCHAR2(255),
    CREATED_AT TIMESTAMP(6)
);

// id값을 1부터 자동으로 1씩 늘려가며 부여해주려면 시퀀스/트리거를 설정해줘야함
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/