-- users 테이블 생성문
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20),
    BUSINESS_TOKEN VARCHAR2(255),
    CREATED_AT TIMESTAMP(6)
);

--id값을 1부터 자동으로 1씩 늘려가며 부여해주려면 시퀀스/트리거를 설정해줘야함
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;

CREATE TABLE BOARDS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200),
    CONTENT CLOB,
    USER_ID NUMBER,
    CREATED_AT TIMESTAMP,
    IS_NOTICE NUMBER(1) DEFAULT 0
);

CREATE TABLE COMMENTS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  USER_ID NUMBER,
  CONTENT CLOB,
  CREATED_AT TIMESTAMP
);

CREATE TABLE FILES(
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  BOARD_ID NUMBER,
  FILE_NAME VARCHAR2(255),
  FILE_PATH VARCHAR2(255),
  UPLOADED_AT TIMESTAMP,
  UPLOADED_BY NUMBER
);

